name: skadi_firebase
description: Utilities class for Firebase.
version: 1.7.0
homepage: https://github.com/lynical-software/skadi_firebase

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ##deps
  cloud_firestore: ^4.15.7
  future_manager: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
